Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2022-12, with the labels that each got.

#419 Add function to compute subiss
  app/routes/__auth/user.server.ts
Labels: backend, auth

#434 Add comment explaining why it is safe to use `sub` without `iss`
  app/routes/__auth/login.ts
  app/routes/__auth/user.server.ts
Labels: backend, auth

#445 Replace moment.js with dayjs
  app/components/CredentialCard.tsx
  app/components/EmailNotificationCard.tsx
  app/components/TimeAgo.tsx
  package-lock.json
  package.json
Labels: backend, dependencies

#447 Don't check expiration of newly refreshed tokens
  app/routes/__auth/user.server.ts
Labels: backend, auth

#446 Add tooltip with UTC time to TimeAgo
  app/components/TimeAgo.tsx
Labels: enhancement, frontend

#448 Clean up handling of OpenID Connect tokens and user sessions
  app/routes/__auth/login.ts
  app/routes/__auth/user.server.ts
Labels: backend, auth

#449 Add local IdP for developing in sandbox mode
  app.arc
  app/routes/__auth/auth.server.ts
  app/routes/__auth/logout.ts
  app/routes/docs/contributing.mdx
  package-lock.json
  package.json
  src/plugins/sandboxOidcIdp.js
Labels: backend, auth

#364 Peer Endorsement Breakout PR 1, Endorsement Backend
  app.arc
  app/routes/user/endorsements.server.ts
  src/plugins/lambdaCognitoPermissions.js
  tsconfig.json
Labels: backend

#451 Save refreshed token in existing session, not a new one
  app/routes/__auth/login.ts
  app/routes/__auth/user.server.ts
Labels: bug, backend, auth

#452 Prevent logging in with duplicated emails
  app/routes/__auth/login.ts
  app/routes/__auth/logout.ts
  app/routes/__auth/post_logout.tsx
  app/routes/__auth/user.server.ts
Labels: enhancement, frontend, backend, auth

#453 Save access token in session
  app/routes/__auth/user.server.ts
Labels: backend, auth

#454 Handle undefined variables in sandboxOidcIdp.js
  src/plugins/sandboxOidcIdp.js
Labels: infrastructure, auth

#465 Update remix to 1.8.2
  package-lock.json
  package.json
Labels: dependencies

#468 Fix Remix live reloading
  app.arc
  src/plugins/remixLiveReload.js
Labels: infrastructure

#467 Reuse handleCredentialLoader
  app/routes/quickstart/credentials.tsx
  app/routes/user/credentials/edit.tsx
Labels: backend

#466 Display descriptions of available scopes
  app/components/NewCredentialForm.tsx
  app/routes/user/client_credentials.server.ts
  src/plugins/lambdaCognitoPermissions.js
Labels: frontend, backend

#471 Add contact link to existing IdP dialog box
  app/routes/__auth/post_logout.tsx
Labels: frontend, auth

#473 Remove unused component
  app/components/Spinner.tsx
Labels: frontend

#472 Rename existingIdp claim to dev:custom:existingIdp
  app/routes/__auth/user.server.ts
Labels: backend, auth

#474 Clean up user profile page
  app/components/Header.tsx
  app/components/Spinner.tsx
  app/routes/__auth/user.server.ts
  app/routes/user.tsx
  app/routes/user/client_credentials.server.ts
  app/routes/user/cognito.server.ts
  app/routes/user/endorsements.server.ts
  app/routes/user/index.tsx
  app/routes/user/user_data.server.ts
  package-lock.json
  package.json
Labels: frontend, backend

#475 Add titles to all pages
  app/root.tsx
  app/routes/$.tsx
  app/routes/circulars.mdx
  app/routes/docs.tsx
  app/routes/docs/client.mdx
  app/routes/docs/contributing.mdx
  app/routes/docs/faq.mdx
  app/routes/docs/index.mdx
  app/routes/docs/roadmap.mdx
  app/routes/docs/styleguide.mdx
  app/routes/index.mdx
  app/routes/missions.tsx
  app/routes/missions/agile.mdx
  app/routes/missions/calet.mdx
  app/routes/missions/fermi.mdx
  app/routes/missions/gecam.mdx
  app/routes/missions/hawc.mdx
  app/routes/missions/icecube.mdx
  app/routes/missions/index.mdx
  app/routes/missions/integral.mdx
  app/routes/missions/konus.mdx
  app/routes/missions/lvk.mdx
  app/routes/missions/maxi.mdx
  app/routes/missions/moa.mdx
  app/routes/missions/sksn.mdx
  app/routes/missions/snews.mdx
  app/routes/missions/swift.md
  app/routes/missions/swift.mdx
  app/routes/news.mdx
  app/routes/notices.tsx
  app/routes/quickstart.tsx
  app/routes/quickstart/alerts.tsx
  app/routes/quickstart/code.tsx
  app/routes/quickstart/credentials.tsx
  app/routes/quickstart/index.tsx
  app/routes/user.tsx
  app/routes/user/credentials.tsx
  app/routes/user/credentials/edit.tsx
  app/routes/user/email.tsx
  app/routes/user/email/edit.tsx
  app/routes/user/index.tsx
Labels: frontend

#476 Add sitemap.xml
  app/entry.server.tsx
  app/otherRootRoutes.server.ts
  app/routes/$.tsx
  app/routes/__auth/post_logout.tsx
  app/routes/quickstart/alerts.tsx
  app/routes/quickstart/code.tsx
  app/routes/quickstart/credentials.tsx
  app/routes/user.tsx
  package-lock.json
  package.json
Labels: seo

#479 Let Remix fingerprint all static assets
  .gitignore
  .prettierignore
  app.arc
  app/components/Footer.tsx
  app/components/Header.tsx
  app/img/Fermi_Gamma-ray_Space_Telescope_logo.svg
  app/img/agile-logo.png
  app/img/calet-logo.png
  app/img/checkbox-indeterminate.svg
  app/img/gcn-classic-over-kafka.svg
  app/img/gcn-classic.svg
  app/img/gcn-diagram.jpg
  app/img/gcn-kafka.svg
  app/img/gecam.jpg
  app/img/hawc-logo.png
  app/img/icecube-logo.png
  app/img/integral-logo.jpg
  app/img/kagra-logo.png
  app/img/logo.svg
  app/img/logo_swift.gif
  app/img/lsc-logo.png
  app/img/maxi-logo.png
  app/img/sk-logo.png
  app/img/snews-logo.jpg
  app/img/virgo-logo.png
  app/root.tsx
  app/routes/index.mdx
  app/routes/missions/agile.mdx
  app/routes/missions/calet.mdx
  app/routes/missions/fermi.mdx
  app/routes/missions/gecam.mdx
  app/routes/missions/hawc.mdx
  app/routes/missions/icecube.mdx
  app/routes/missions/integral.mdx
  app/routes/missions/lvk.mdx
  app/routes/missions/maxi.mdx
  app/routes/missions/sksn.mdx
  app/routes/missions/snews.mdx
  app/routes/missions/swift.mdx
  gulpfile.js
  package.json
Labels: enhancement, frontend

#480 Update remix to 1.9.0
  package-lock.json
  package.json
Labels: dependencies

#481 Correct type for arc.tables().db._doc
  app/routes/user/endorsements.server.ts
  package-lock.json
  package.json
Labels: backend, types

#485 Add function to auto-increment DynamoDB tables
  app/lib/dynamoDBAutoIncrement.ts
  package-lock.json
  package.json
Labels: backend

#487 Convert remix.config from cjs to mjs
  remix.config.js
  remix.config.mjs
Labels: infrastructure

#486 Factor out reusable input hint component
  app/components/Hint.tsx
  app/routes/user/index.tsx
Labels: frontend

#489 Add unit tests for dynamoDBAutoIncrement, and fix some bugs
  .github/workflows/node.js.yml
  .gitignore
  __tests__/lib/dynamoDBAutoIncrement.ts
  app/lib/dynamoDBAutoIncrement.ts
  jest-dynamodb-config.js
  package-lock.json
  package.json
Labels: bug, backend
