Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2022-05, with the labels that each got.

#56 Homepage: explain Kafka better with graphics and tables
  app/img/gcn-classic-over-kafka.svg
  app/img/gcn-classic.svg
  app/img/gcn-kafka.svg
  app/routes/index.md
  app/routes/index.mdx
  theme/custom.scss
Labels: content

#62 Move images to public assets directory
  app/components/Footer.tsx
  app/components/Header.tsx
  app/routes/index.mdx
  public/img/gcn-classic-over-kafka.svg
  public/img/gcn-classic.svg
  public/img/gcn-kafka.svg
  public/img/logo.svg
Labels: frontend, content

#61 Add link for good first issues
  app/routes/docs/contributing.mdx
Labels: content

#63 Missions
  app/img/virgo.png
  app/routes/missions.md
  app/routes/missions.tsx
  app/routes/missions/fermi.md
  app/routes/missions/gcnmissions.md
  app/routes/missions/index.ts
  app/routes/missions/swift.md
  public/img/Fermi_Gamma-ray_Space_Telescope_logo.svg
  public/img/logo_swift.gif
Labels: content

#64 Tweak missions section index page and title
  app/routes/missions.tsx
  app/routes/missions/index.ts
  app/routes/missions/missions.md
Labels: content

#69 Add site banner to indicate if site is dev version
  app/components/DevBanner.tsx
  app/components/Header.tsx
  app/root.tsx
Labels: frontend, infrastructure

#71 Add user icon to data flow diagrams
  public/img/gcn-classic-over-kafka.svg
  public/img/gcn-classic.svg
  public/img/gcn-kafka.svg
Labels: content

#73 Add 404 error page
  app/root.tsx
  app/routes/$.tsx
Labels: frontend

#76 Change SWIFT_XRT_POS_NACK to SWIFT_XRT_CENTROID
  app/routes/missions/swift.md
Labels: content

#80 Get rid of redirects for sidenav pages
  app/routes/docs.tsx
  app/routes/docs/index.md
  app/routes/docs/index.ts
  app/routes/missions.tsx
  app/routes/missions/index.md
  app/routes/missions/index.ts
Labels: frontend, content

#78 Don't show progress bar if transition is very quick
  app/root.tsx
  package-lock.json
  package.json
Labels: frontend

#75 GCN Circulars style guide addition
  app/routes/circulars.mdx
  app/routes/docs.tsx
  app/routes/docs/styleguide.md
Labels: content

#82 Refactor authentication
  app/components/Header.tsx
  app/lib/ClientCredentialVendingMachine.server.ts
  app/lib/auth.server.ts
  app/root.tsx
  app/routes/__auth/auth.server.ts
  app/routes/__auth/login.ts
  app/routes/__auth/logout.ts
  app/routes/__auth/user.server.ts
  app/routes/auth.ts
  app/routes/login.ts
  app/routes/logout.ts
Labels: backend

#84 Do not track issuer in session key and database
  app.arc
  app/lib/ClientCredentialVendingMachine.server.ts
  app/routes/__auth/auth.server.ts
  app/routes/__auth/login.ts
  app/routes/__auth/user.server.ts
  package-lock.json
  package.json
Labels: backend
