Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2023-02, with the labels that each got.

#566 Update remix to 1.12.0
  package-lock.json
  package.json
Labels: dependencies

#577 Pin AWS SDK packages
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#580 Slim down prometheus.ts file size by preprocessing it
  app/components/NoticeTypeCheckboxes.tsx
  app/lib/prometheus.ts
Labels: frontend

#579 Change page title to "Peer Endorsements"
  app/components/Header.tsx
  app/routes/user.tsx
  app/routes/user/endorsements.tsx
Labels: frontend

#582 Add loading spinner to combo box
  app/routes/user/endorsements.tsx
Labels: frontend

#581 Remove unnecessary duplicate fetchers
  app/routes/user/endorsements.tsx
Labels: frontend

#590 Clean up ternary expressions in React JSX fragments
  app/components/NestedCheckboxes.tsx
  app/routes/notices.tsx
  app/routes/user/email/index.tsx
  app/routes/user/endorsements.tsx
Labels: frontend

#591 Convert Remix mdx from function to const object
  remix.config.mjs
Labels: frontend

#592 Factor hero into a separate component
  app/components/Hero.tsx
  app/routes/index.mdx
Labels: frontend

#594 Fix paragraph styling
  app/components/CredentialCard.tsx
  app/components/EmailNotificationCard.tsx
  app/components/NewCredentialForm.tsx
  app/components/UserPageContainer.tsx
  app/root.tsx
  app/routes/$.tsx
  app/routes/__auth/post_logout.tsx
  app/routes/circulars/$circularId.tsx
  app/routes/circulars/index.tsx
  app/routes/docs.tsx
  app/routes/missions.tsx
  app/routes/notices.tsx
  app/routes/quickstart/alerts.tsx
  app/routes/quickstart/credentials.tsx
  app/routes/quickstart/index.tsx
  app/routes/user.tsx
  app/routes/user/credentials/index.tsx
  app/routes/user/email/index.tsx
  app/routes/user/endorsements.tsx
  app/routes/user/index.tsx
  remix.config.mjs
  theme/custom.scss
Labels: frontend

#597 Reuse getDynamoDBAutoIncrement in email-incoming handler
  app/email-incoming/index.ts
  app/routes/circulars/circulars.server.ts
Labels: backend

#599 Remove unnecessary grid containers
  app/components/HeadingWithAddButton.tsx
  app/components/UserPageContainer.tsx
  app/routes/user/credentials.tsx
  app/routes/user/credentials/edit.tsx
  app/routes/user/credentials/index.tsx
  app/routes/user/email.tsx
  app/routes/user/email/edit.tsx
  app/routes/user/email/index.tsx
  app/routes/user/endorsements.tsx
Labels: frontend

#598 Remove guesswork about URL origin, refactor email sending
  app/email-incoming/index.ts
  app/lib/email.ts
  app/lib/env.ts
  app/root.tsx
  app/routes/docs/contributing.mdx
  app/routes/user/email_notifications.server.ts
  src/plugins/emailIncoming.mjs
Labels: backend

#601 Add clean script to remove most files created by build and deploy
  package.json
Labels: javascript

#600 Remove names from default exports in route modules
  app/routes/circulars/$circularId.tsx
  app/routes/circulars/index.tsx
  app/routes/circulars/new.tsx
  app/routes/docs.tsx
  app/routes/missions.tsx
  app/routes/notices.tsx
  app/routes/quickstart.tsx
  app/routes/quickstart/alerts.tsx
  app/routes/quickstart/code.tsx
  app/routes/quickstart/credentials.tsx
  app/routes/quickstart/index.tsx
  app/routes/user.tsx
  app/routes/user/credentials/edit.tsx
  app/routes/user/credentials/index.tsx
  app/routes/user/email/edit.tsx
  app/routes/user/email/index.tsx
  app/routes/user/endorsements.tsx
  app/routes/user/index.tsx
Labels: frontend

#602 Exclude node_modules from esbuild bundling
  esbuild.mjs
  package.json
Labels: javascript

#605 Depend on released version of @architect/plugin-lambda-invoker
  package-lock.json
  package.json
Labels: dependencies

#604 Fix typo in CloudFormation template
  src/plugins/emailIncoming.mjs
Labels: backend, infrastructure

#603 Make concurrency and tracing settings apply only to web site lambda
  app.arc
  server/config.arc
  src/plugins/tracing.mjs
Labels: backend, infrastructure

#606 Factor circular submitters group into a constant
  app/email-incoming/index.ts
  app/routes/circulars/circulars.server.ts
  app/routes/circulars/new.tsx
  app/routes/user/endorsements.server.ts
Labels: backend

#613 Update remix to 1.13.0
  package-lock.json
  package.json
Labels: dependencies

#608 Endorsement UX
  app/routes/circulars/new.tsx
  app/routes/user/endorsements.server.ts
  app/routes/user/endorsements.tsx
Labels: frontend, backend

#617 Enable Point In Time Recovery for all tables except sessions
  app.arc
Labels: infrastructure

#635 Update AWS OTEL Lambda layer
  package-lock.json
  package.json
  server/collector.yaml
  server/tracing.js
  src/plugins/tracing.mjs
Labels: backend, infrastructure

#565 added documentation for new producers
  app/routes/docs.tsx
  app/routes/docs/producers.mdx
Labels: documentation

#619 Implement GCN Circulars search field using OpenSearch
  app.arc
  app/email-incoming/index.ts
  app/lib/search.server.ts
  app/routes/circulars/circulars.server.ts
  app/routes/circulars/index.tsx
  package-lock.json
  package.json
Labels: backend

#637 email-incoming Lambda errors out if circulars feature is disabled
  app/email-incoming/index.ts
  app/lib/env.server.ts
  app/root.tsx
  app/routes/circulars/index.tsx
  app/routes/circulars/new.tsx
Labels: backend
