Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2023-05, with the labels that each got.

#891 Add function to get basic auth headers
  app/lib/__tests__/headers.server.ts
  app/lib/headers.server.ts
Labels: backend

#892 Display Circular date in seconds, not ms, precision
  app/routes/circulars/$circularId.tsx
  app/routes/circulars/circulars.lib.ts
Labels: enhancement, frontend

#897 Allow sending emails from a configuration set
  src/plugins/sendEmailPermissions.mjs
Labels: backend, email

#899 Add year headings to news page
  app/routes/news.mdx
Labels: frontend

#900 Set news items to fill page width
  app/routes/news.mdx
Labels: frontend

#901 Remove redundant position-absolute
  app/components/Highlight.tsx
Labels: frontend

#902 Fix some accessibility issues with the main section
  app/root.tsx
Labels: frontend, accessibility

#919 Add titles to Circulars pages
  app/root.tsx
  app/routes/circulars.tsx
  app/routes/circulars/$circularId.tsx
  app/routes/circulars/new.tsx
Labels: frontend

#920 Move GridContainer from root route to top-level routes
  app/components/Hero.tsx
  app/root.tsx
  app/routes/circulars.tsx
  app/routes/contact.tsx
  app/routes/docs.tsx
  app/routes/index.mdx
  app/routes/missions.tsx
  app/routes/news.mdx
  app/routes/notices.tsx
  app/routes/quickstart.tsx
  app/routes/user.tsx
Labels: frontend

#925 Make hero image fill page width with star field
  app/components/Hero.tsx
  app/img/gcn-diagram.jpg
  app/img/hero/center-cropped.jpg
  app/img/hero/center.jpg
  app/img/hero/left.jpg
  app/img/hero/right.jpg
  build/theme/custom.scss
Labels: frontend

#931 Disable OpenTelemetry tracing
  app.arc
  package-lock.json
  package.json
Labels: backend

#934 Optimize image loading
  app/components/Hero.tsx
  app/routes/index.mdx
  app/routes/missions/agile.mdx
  app/routes/missions/calet.mdx
  app/routes/missions/fermi.mdx
  app/routes/missions/gecam.mdx
  app/routes/missions/hawc.mdx
  app/routes/missions/icecube.mdx
  app/routes/missions/integral.mdx
  app/routes/missions/lvk.mdx
  app/routes/missions/maxi.mdx
  app/routes/missions/sksn.mdx
  app/routes/missions/snews.mdx
  app/routes/missions/swift.mdx
Labels: frontend

#797 Enable client-side routing for all Markdown links
  app/root.tsx
  package-lock.json
  package.json
Labels: frontend

#936 Revert "Enable client-side routing for all Markdown links"
  app/root.tsx
  package-lock.json
  package.json
Labels: frontend

#937 Send Circulars using To addresses, not Bcc
  app.arc
  app/lib/email.server.ts
  app/table-streams/circulars/index.ts
  src/plugins/emailOutgoing.mjs
Labels: backend, email

#947 Fix bug in printf statement, too many arguments
  app/components/ClientSampleCode.tsx
Labels: documentation, content

#946 Locate librdkafka headers and libs using pkg-config
  app/components/ClientSampleCode.tsx
Labels: documentation, frontend

#953 Remove spurious 'the'
  app/routes/user/email_notices.server.ts
Labels: frontend

#951 User menu should behave as a simple link if JS is disabled
  app/components/Header.tsx
Labels: frontend

#952 AGILE is an acronym. Capitalize it
  app/components/NoticeTypeCheckboxes.tsx
Labels: frontend

#954 Fix typo
  app/routes/user/index.tsx
Labels: frontend

#955 Fix typo (again)
  app/routes/user/index.tsx
Labels: frontend

#967 [nasa-gcn/gcn.nasa.gov#923] back now returns to search output
  app/routes/circulars/$circularId.tsx
  app/routes/circulars/index.tsx
Labels: frontend

#979 Fix CSS classes on grid containers in error pages
  app/root.tsx
Labels: bug, frontend

#980 Use parseFloat to process circular IDs for DDB lookup
  app/routes/circulars/$circularId.json.ts
  app/routes/circulars/$circularId.raw.ts
  app/routes/circulars/$circularId.tsx
Labels: bug, backend

#982 Fix 404 error in circular detail route
  app/routes/circulars/$circularId.tsx
Labels: bug, backend

#977 Fix Remix v2 fetcher API warnings
  app/components/EmailNotificationCard.tsx
  app/routes/user/email/index.tsx
  app/routes/user/index.tsx
Labels: backend

#986 Speed up Typescript by saving incremental progress
  .github/workflows/node.js.yml
  .gitignore
  .prettierignore
  lint-staged.config.mjs
  package.json
  tsconfig.json
Labels: infrastructure, types

#985 Tune remix config for dev and production
  remix.config.mjs
Labels: infrastructure, javascript

#978 Add honors and awards
  app/routes/index.mdx
Labels: enhancement, content
