Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2023-09, with the labels that each got.

#1318 Deploy static assets to a subdir of the static bucket
  app.arc
  remix.config.mjs
  src/plugins/lambdaMayNotWriteToStaticBucket.mjs
Labels: infrastructure

#1315 Update ADS weekly
  app.arc
  app/routes/circulars.$circularId.tsx
  app/routes/docs.circulars.archive.mdx
Labels: frontend, backend

#1335 Move postcss config to package.json
  package.json
  postcss.config.js
Labels: frontend, infrastructure

#1336 Highlight Sample Code sidenav link when page is active
  app/routes/docs.tsx
Labels: bug, frontend, content

#1288 Minor clode cleanup in makeTarFile
  app/routes/circulars/circulars.server.ts
Labels: backend

#1338 Infer useLoaderData type, handle corner cases where things are null
  app/routes/docs_.schema.tsx
Labels: bug, frontend, types

#1345 Stupid, stupid, stupid!
  app/routes/circulars.archive[.]$suffix[.]tar.ts
Labels: bug

#1347 Switch to using static routes for archive redirects
  app/routes/circulars.archive[.]$suffix[.]tar.ts
  app/routes/circulars.archive[.]json[.]tar.ts
  app/routes/circulars.archive[.]txt[.]tar.ts
  app/scheduled/circulars/uploadTar.ts
Labels: bug

#1352 Fix postcss-csso configuration
  package.json
Labels: bug, frontend, infrastructure

#1353 Fix code indentation on news page
  app/routes/news.mdx
Labels: bug, content

#1357 Update contributing guide for Remix v2 route module convention
  app/routes/docs.contributing._index.mdx
Labels: bug, documentation, content

#1354 Refactor scheduled circulars Lambda
  app/routes/circulars.archive[.]json[.]tar[.]gz.ts
  app/routes/circulars.archive[.]txt[.]tar[.]gz.ts
  app/scheduled/circulars/actions.ts
  app/scheduled/circulars/actions/stats.ts
  app/scheduled/circulars/actions/tar.ts
  app/scheduled/circulars/circularAction.ts
  app/scheduled/circulars/index.ts
  app/scheduled/circulars/storage.ts
Labels: backend

#1377 Update remix to 2.0.0
  app/entry.server.tsx
  app/lib/schema-data.server.ts
  app/root.tsx
  app/root/Title.tsx
  app/routes/_auth.post_logout.tsx
  package-lock.json
  package.json
  remix.config.mjs
  tsconfig.json
Labels: dependencies, javascript

#1390 Display Circular text in monospace font
  app/routes/circulars.$circularId/route.tsx
Labels: frontend

#1391 Transform literal URLs in Circulars into hyperlinks
  app/routes/circulars.$circularId/body.tsx
  app/routes/circulars.$circularId/rehypeAutolinkLiteral.ts
  package-lock.json
  package.json
Labels: enhancement, frontend

#1402 Preserve leading whitespace in GCN Circulars
  app/routes/circulars.$circularId/PlainTextBody.module.scss
  app/routes/circulars.$circularId/PlainTextBody.tsx
  app/routes/circulars.$circularId/route.tsx
Labels: frontend

#1401 Add news for September 2023
  app/root.tsx
  app/routes/circulars._index.tsx
  app/routes/news.mdx
Labels: content

#1414 Convert from CJS to ESM
  __mocks__/openid-client.js
  app/email-incoming/circulars/index.ts
  app/email-incoming/support/index.ts
  app/scheduled/ads/index.ts
  app/scheduled/circulars/index.ts
  app/table-streams/circulars/index.ts
  esbuild.js
  lint-staged.config.js
  package.json
  remix.config.js
  sandbox-invoke-mocks.js
  sandbox-search.js
  server.ts
  src/plugins/email-incoming.js
  src/plugins/emailOutgoing.js
  src/plugins/lambdaCognitoPermissions.js
  src/plugins/missionCloudPlatform.js
  src/plugins/plugin-remix.js
  src/plugins/sandboxOidcIdp.js
  src/plugins/staticBucketPermissions.js
Labels: infrastructure, javascript

#1426 Skip prettier on Windows in CI pipeline
  .github/workflows/node.js.yml
Labels: github_actions

#1429 Add FAQ on operations during a government shutdown
  app/components/NewsBanner.tsx
  app/root.tsx
  app/routes/docs.faq.md
  app/routes/docs.tsx
Labels: documentation, content

#1428 Add all GCN Circulars to site map
  app/lib/sitemap.server.ts
  app/routes/_seo.robots[.]txt.ts
  app/routes/_seo.sitemap_index[.]xml.ts
  app/scheduled/circulars/actions/sitemap.ts
  app/scheduled/circulars/actions/stats.ts
  app/scheduled/circulars/actions/tar.ts
  app/scheduled/circulars/index.ts
  app/scheduled/circulars/storage.ts
Labels: seo

#1431 Set MIME type and cache control for generated files
  app/scheduled/circulars/actions/sitemap.ts
  app/scheduled/circulars/actions/stats.ts
  app/scheduled/circulars/actions/tar.ts
  app/scheduled/circulars/storage.ts
Labels: backend

#1434 Update government shutdown FAQ
  app/root.tsx
  app/routes/docs.faq.md
Labels: documentation, frontend

#1433 Remove unnecessary JSX fragment
  app/routes/_index/route.mdx
Labels: frontend, maintenance

#1432 Add usa-link class to most <Link> components
  app/components/CircularsKeywords.tsx
  app/components/ClientSampleCode.tsx
  app/components/nested-checkboxes/NestedCheckboxes.tsx
  app/root.tsx
  app/routes/circulars.$circularId/PlainTextBody.tsx
  app/routes/circulars._index.tsx
  app/routes/contact.tsx
  app/routes/docs.contributing.deployment/route.mdx
  app/routes/docs_.schema.$version.$/components.tsx
  app/routes/docs_.schema.$version.$/route.tsx
  app/routes/docs_.schema.$version._index.tsx
  app/routes/docs_.schema.tsx
  app/routes/notices.tsx
  app/routes/quickstart.alerts.tsx
  app/routes/user.credentials._index.tsx
  app/routes/user.email._index/route.tsx
  app/routes/user.endorsements/route.tsx
Labels: frontend

#1435 Refactor AstroData
  app/routes/circulars.$circularId/AstroData.components.tsx
  app/routes/circulars.$circularId/AstroData.tsx
  app/routes/circulars.$circularId/PlainTextBody.tsx
Labels: frontend

#1245 Schema Design under New Notices docs #1196
  app/routes/docs.notices.producers/ProducerSampleCode.tsx
  app/routes/docs.notices.producers/route.mdx
  app/routes/docs.notices.schema.mdx
  app/routes/docs.tsx
Labels: documentation

#1448 Update sandbox seed
  sandbox-seed.json
Labels: maintenance

#1452 Enable client-side routing for breadcrumbs
  app/routes/docs_.schema.$version.$/BreadcrumbNav.tsx
Labels: enhancement, frontend

#1460 Don't use default import for ReCAPTCHA
  app/components/ReCAPTCHA.tsx
Labels: bug
