Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2023-10, with the labels that each got.

#1475 Provide link text for mission archives
  app/routes/missions.agile/route.mdx
  app/routes/missions.calet/route.mdx
  app/routes/missions.fermi/route.mdx
  app/routes/missions.gecam/route.mdx
  app/routes/missions.hawc/route.mdx
  app/routes/missions.icecube/route.mdx
  app/routes/missions.integral/route.mdx
  app/routes/missions.konus.mdx
  app/routes/missions.lvk/route.mdx
  app/routes/missions.maxi/route.mdx
  app/routes/missions.moa.mdx
  app/routes/missions.sksn/route.mdx
  app/routes/missions.snews/route.mdx
  app/routes/missions.swift/route.mdx
Labels: content

#1474 Remove overly general word break CSS rule for anchors
  app/theme.scss
Labels: frontend

#1473 Replace archive download modal with links with file sizes
  app/routes/circulars._archive._index.tsx
  app/routes/circulars._archive.tsx
  app/scheduled/circulars/actions/tar.ts
  package-lock.json
  package.json
  remix.config.js
Labels: frontend

#1458 Add API for third parties to post GCN Circulars on behalf of users
  __tests__/cognito.server.ts
  app/email-incoming/circulars/index.ts
  app/lib/cognito.server.ts
  app/routes/_auth/user.server.ts
  app/routes/api.circulars.ts
  app/routes/circulars.$circularId/FrontMatter.tsx
  app/routes/circulars/circulars.lib.ts
  app/routes/circulars/circulars.server.ts
  app/routes/circulars/route.tsx
  app/routes/user.endorsements/endorsements.server.ts
Labels: enhancement, backend, auth

#1484 Refactor root meta function as meta tags
  app/root.tsx
Labels: seo

#1487 Fix visual artifact due to doubled breadcrumb
  app/routes/docs_._schema-browser.schema.($version).$/BreadcrumbNav.tsx
Labels: bug, frontend

#1492 Add page titles to schema browser
  app/routes/docs_._schema-browser.schema.($version).$/route.tsx
  app/routes/docs_._schema-browser.tsx
Labels: frontend

#1507 Fix version selector toggle
  app/routes/docs_._schema-browser.schema.($version).$/route.tsx
Labels: bug, frontend

#1508 Adjust handling of DetailsDropdownContent props
  app/components/DetailsDropdownContent.tsx
Labels: frontend

#1509 Remove unnecessary fragment
  app/routes/docs_._schema-browser.schema.($version).$/route.tsx
Labels: maintenance

#1510 Remove unnecessary reexport
  app/lib/search.server.ts
  app/routes/circulars/circulars.server.ts
  app/table-streams/circulars/index.ts
Labels: maintenance

#1518 Create hyperlinks for TNS transients in Circulars
  app/routes/circulars.$circularId/AstroData.components.tsx
Labels: enhancement, frontend

#1520 Remove rel="external" from AstroData links
  app/routes/circulars.$circularId/AstroData.components.tsx
Labels: bug, frontend

#1521 Clean up whitespace
  app.arc
  app/components/ClientSampleCode.tsx
  app/email-incoming/circulars/index.ts
  app/routes/docs.notices.producers.mdx
  app/routes/missions.icecube/route.mdx
  app/routes/user.endorsements/endorsements.server.ts
  app/theme.scss
Labels: maintenance

#1525 Add preview and syntax reference for GCN Circulars editor
  app/routes/circulars.$circularId/AstroData.components.tsx
  app/routes/circulars.$circularId/AstroDataContext.tsx
  app/routes/circulars.$circularId/Body.tsx
  app/routes/circulars.$circularId/PlainTextBody.module.scss
  app/routes/circulars.$circularId/route.tsx
  app/routes/circulars.new.tsx
  remix.config.js
Labels: enhancement

#1534 Allow cognito-idp:AdminGetUser AWS IAM action
  src/plugins/lambdaCognitoPermissions.js
Labels: backend

#1535 Adjust Circulars syntax table style: compact, bordered
  app/routes/circulars.new.tsx
Labels: frontend

#1544 Fix indeterminate checkbox state in JSON notice type format tab
  app/components/NoticeTypeCheckboxes/NoticeTypeCheckboxes.tsx
  app/components/nested-checkboxes/NestedCheckboxes.tsx
Labels: bug, frontend

#1547 Retarget legacy GCN Circulars links to new archive
  app/routes/docs.faq.md
  app/routes/missions.agile/route.mdx
  app/routes/missions.calet/route.mdx
  app/routes/missions.fermi/route.mdx
  app/routes/missions.hawc/route.mdx
  app/routes/missions.integral/route.mdx
  app/routes/missions.konus.mdx
  app/routes/missions.lvk/route.mdx
  app/routes/missions.maxi/route.mdx
  app/routes/missions.swift/route.mdx
  app/routes/news.mdx
Labels: content, maintenance

#1549 Fix incorrect imports in Python offsets example
  app/routes/docs.client.samples.md
Labels: bug, content

#1557 Fix type inference for useLoaderData
  app/routes/_auth.post_logout.tsx
Labels: maintenance

#1580 Add news item for Zendesk
  app/root.tsx
  app/routes/news.mdx
Labels: content

#1587 Fix zero rate estimate display for JSON notice types
  app/components/NoticeTypeCheckboxes/NoticeTypeCheckboxes.tsx
Labels: bug, frontend

#1588 Replace some Wikipedia links
  app/routes/docs.circulars.archive.mdx
  app/routes/docs.circulars.submitting.mdx
  app/routes/docs.notices.schema.mdx
Labels: content

#1589 Guano icecube announcement news
  app/root.tsx
  app/routes/missions.swift/route.mdx
  app/routes/news.mdx
Labels: content

#1599 Add Python Lambda
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
  .gitignore
  app.arc
  lint-staged.config.js
  package-lock.json
  package.json
  python/config.arc
  python/lambda.py
  requirements.txt
Labels: backend
