Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2024-01, with the labels that each got.

#1797 Move hardcoded title out of generic element
  app/components/DetailsDropdownButton.tsx
  app/routes/_gcn.docs_._schema-browser.schema.($version).$/route.tsx
Labels: bug, maintenance

#1795 Remove unnecessary explicit className prop
  app/components/DetailsDropdownButton.tsx
Labels: maintenance

#1782 Configure OIDC token revocation
  app/routes/_gcn._auth/auth.server.ts
Labels: enhancement, auth

#1801 Switch back to installing nasawds from NPM
  package-lock.json
  package.json
Labels: dependencies

#1804 Segmented radio button with output in form data
  app/routes/_gcn.circulars.edit.$circularId/CircularEditForm.tsx
  app/routes/_gcn.circulars.edit.$circularId/SegmentedRadioButton.tsx
Labels: frontend

#1837 Add comment for dark mode section of style sheet
  app/theme.scss
Labels: maintenance

#1839 adding missing image file
  app/routes/labs.missions/mission-timeline.png
Labels: bug, content

#1840 Test build and Python dep installation in PR workflow
  .github/workflows/pull_request.yml
Labels: enhancement, infrastructure

#1841 Add Python installation to local dev instructions
  app/routes/_gcn.docs.contributing._index.mdx
Labels: documentation, content

#1842 Update content route filenames in contributing guide
  app/routes/_gcn.docs.contributing._index.mdx
Labels: bug, documentation

#1859 Update Node.js version to 20.x
  app.arc
  package-lock.json
  package.json
Labels: dependencies

#1869 Update aws-sdk packages to 3.462.2
  package-lock.json
  package.json
Labels: dependencies

#1873 Remove News from navbar
  app/routes/_gcn/header/Header.tsx
Labels: frontend

#1876 Ignore python/vendor directory
  pyproject.toml
Labels: python
