Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2024-03, with the labels that each got.

#2002 Fix bugs in createSynonyms
  app/routes/_gcn.synonyms/synonyms.server.ts
Labels: bug, maintenance

#2003 Remove duplicate validation in putSynonyms
  app/routes/_gcn.synonyms/synonyms.server.ts
Labels: maintenance

#2017 Unify tab UI design across site
  app/components/tabs/Tabs.tsx
  app/components/tabs/exclusiveGroup.tsx
  app/components/tabs/index.module.scss
  app/components/tabs/index.tsx
  app/components/tabs/tabs.module.scss
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/Tabs.tsx
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/index.tsx
  app/routes/_gcn.docs.notices.schema.mdx
  app/routes/_gcn.docs_._schema-browser.schema.($version).$/route.tsx
  app/routes/_gcn.quickstart.code.tsx
Labels: enhancement, frontend, maintenance

#2016 Consistently add <p> tags in client sample code
  app/components/ClientSampleCode.tsx
Labels: bug, frontend, maintenance

#2039 Tell git to ignore Python coverage files
  .gitignore
Labels: maintenance

#2041 Use Node 20.x in CI workflows
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
Labels: maintenance

#1975 ACROSS API: Add BurstCube TOO CRUD API
  app.arc
  python/across_api/base/api.py
  python/across_api/base/constraints.py
  python/across_api/base/depends.py
  python/across_api/base/ephem.py
  python/across_api/base/schema.py
  python/across_api/burstcube/api.py
  python/across_api/burstcube/schema.py
  python/across_api/burstcube/toorequest.py
  python/requirements.in
  python/requirements.txt
Labels: enhancement, blocked

#2078 ACROSS API: Add TOO history recording
  app.arc
  python/across_api/burstcube/toorequest.py
  python/requirements.in
  python/requirements.txt
Labels: enhancement, python

#1997 news item for announcements
  app/routes/_gcn.news._index.mdx
  app/routes/_gcn/route.tsx
Labels: content

#2101 ACROSS API: Support Decimal values when converting numerical angles to u.Quantity
  python/across_api/base/schema.py
Labels: bug

#2121 Roll back USWDS to 3.7.1
  app/img/checkbox-indeterminate.svg
  app/theme.scss
  package-lock.json
  package.json
Labels: bug

#2130 Remove direct dependency on @octokit/request-error
  package-lock.json
  package.json
Labels: maintenance

#2134 Fix ugly line break in ADS button on mobile
  app/routes/circulars.$circularId.($version)/route.tsx
Labels: bug

#2137 Remove duplicate CSS property
  app/routes/circulars.edit.$circularId/RichEditor/index.module.scss
Labels: maintenance

#2138 Undo npm override left over from ACROSS
  package-lock.json
  package.json
Labels: maintenance
