Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2024-02, with the labels that each got.

#1898 Add instructions for Java
  app/components/ClientSampleCode.tsx
  app/components/Highlight.tsx
  app/routes/_gcn.docs.client._index.mdx
  app/routes/_gcn.docs.tsx
  app/routes/_gcn.quickstart.code.tsx
  package-lock.json
  package.json
  remix.config.js
Labels: documentation, content

#1900 kafka-console-consumer only supports a single topic
  app/components/ClientSampleCode.tsx
Labels: bug, documentation, content

#1903 Remove unused imports
  python/across_api/base/schema.py
Labels: maintenance

#1902 Configure flake8 and mypy to ignore vendor directory
  .flake8
  pyproject.toml
Labels: maintenance

#1878 ACROSS API: Add unit tests for Ephemeris calculations and others
  python/across_api/base/schema.py
  python/across_api/base/tle.py
  python/across_api/burstcube/ephem.py
  python/across_api/swift/ephem.py
  python/tests/across/__init__.py
  python/tests/across/conftest.py
  python/tests/across/test_across_resolve.py
  python/tests/across/test_env.py
  python/tests/ephem/__init__.py
  python/tests/ephem/conftest.py
  python/tests/ephem/test_burstcube_ephem.py
  python/tests/ephem/test_swift_ephem.py
  requirements.txt
Labels: python

#1939 Remove duplicate keyword
  app/routes/_gcn.circulars/circulars.lib.ts
Labels: bug, frontend

#1956 Fix black line beneath nav on mobile
  app/theme.scss
Labels: bug, frontend

#1941 Fix disclosure arrows not showing up on mobile
  app/routes/_gcn.circulars.edit.$circularId/CircularEditForm.tsx
Labels: bug, frontend

#1959 Clean up Circulars validation and preprocessing
  app/routes/_gcn.api.circulars.ts
  app/routes/_gcn.circulars/circulars.lib.ts
  app/routes/_gcn.circulars/circulars.server.ts
Labels: backend

#1963 Remove old, silly CSS rule
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/index.module.scss
Labels: bug, frontend

#1962 Automatically continue lists and indentation on enter
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/index.tsx
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/onKeyDown.ts
Labels: frontend

#1965 Add icon to plain text button
  app/routes/_gcn.circulars.edit.$circularId/RichEditor/index.tsx
Labels: enhancement, frontend

#1927 Across api add fov
  python/across_api/base/footprint.py
  python/across_api/base/fov.py
  python/across_api/base/pointing.py
  python/across_api/burstcube/fov.py
  python/across_api/swift/fov.py
  python/requirements.in
  python/requirements.txt
  python/tests/fov/__init__.py
  python/tests/fov/conftest.py
  python/tests/fov/test_burstcube_fovcheck.py
  python/tests/fov/test_swift_fovcheck.py
Labels: enhancement

#1635 Code of Conduct
  app/routes/_gcn.docs.code-of-conduct.md
  app/routes/_gcn.docs.tsx
Labels: documentation, frontend
