Repository nasa-gcn/gcn.nasa.gov, pull requests merged in 2024-04, with the labels that each got.

#2190 Use https for arXiv query
  app/routes/circulars.$circularId.($version)/AstroData.components.tsx
Labels: bug

#2152 BurstCube Mission page
  app/routes/missions.burstcube/logo.png
  app/routes/missions.burstcube/route.mdx
  app/routes/missions.tsx
Labels: content

#2203 Rerun prettier on Einstein Probe mission page
  app/routes/missions.einsteinprobe/route.mdx
Labels: maintenance

#2204 Rename einsteinprobe route to einstein-probe
  app/routes/missions.einstein-probe/logo.svg
  app/routes/missions.einstein-probe/route.mdx
  app/routes/missions.tsx
Labels: maintenance

#2191 add content to corrections docs
  app/routes/circulars.moderation.tsx
  app/routes/docs.circulars._index.mdx
  app/routes/docs.circulars.corrections.mdx
  app/routes/docs.circulars.corrections/request_correction_button.png
  app/routes/docs.circulars.corrections/route.mdx
  app/routes/docs.circulars.corrections/version_button.png
Labels: documentation

#2208 Add warning about distinct API key values in deployment stages
  app/routes/docs.contributing.configuration/route.mdx
Labels: documentation

#2207 Remove SpaceTrack configuration, only used by ACROSS
  app/routes/docs.contributing.configuration/route.mdx
Labels: maintenance

#2212 Work around some ideosyncrasies in ADS pub info
  app/routes/api.tooltip.doi.$.ts
Labels: bug

#2223 Clean up TNS alternate event names
  app/routes/api.tooltip.tns.$.ts
  app/routes/circulars.$circularId.($version)/AstroData.components.tsx
Labels: bug

#2228 Permit requests that come via the CDN, reject all others
  app/routes/docs.contributing.configuration/route.mdx
  server.ts
Labels: enhancement, backend
